config/routes.rb
Rails.application.routes.draw do
  resources :status_updates

  resources :profiles

  devise_for :users
  get 'home/index'

root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
  belongs_to :user
  def self.reverse_order
  	order(created_at: :desc)
  	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :status_updates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  	@animal = ['Dog','Cat','Horse','Monkey','Bird','Fish','Turtle','Frog',]
  	@name = 'Robert'
  	@greeting = 'G\'day'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @status_update = StatusUpdate.new
    @status_updates = @profile.user.status_updates.reverse_order

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :hobbies, :dob, :user_id)
    end
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)
    @status_update.user = current_user
    respond_to do |format|
      if @status_update.save
        format.html { redirect_to :back, notice: 'Status update was successfully created.' }
        format.json { render :show, status: :created, location: @status_update }
      else
        format.html { render :new }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_update }
      else
        format.html { render :edit }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to status_updates_url, notice: 'Status update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:user_id, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/home/index.html.erb
<h1>The Coder Factory<br>
Learn to Code: Weekend Workshop <span class="glyphicon glyphicon-upload"></span></h1>
<h3><%= @greeting +" "+ @name %></h3>
<hr>
<a href="http://www.google.com.au"><img src="http://dropdeadgorgeousdaily.com/wp-content/uploads/2013/06/net-a-porter-sale-640x239.jpg" alt="SALE!" title="The greatest sale in the world" class="img-responsive"></a>
<div style="width:640px; " >
	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
	<p><a href="http://www.google.com.au">Google's</a></p>
<hr>
<ul>
	<li><%= @animal [0] == 'Horse' or 'Cat' %></li>
	<li><% if (@animal == 'Horse') %>Nay<%else%>Not nay<% end %></li>
	<li><%= @animal [1] %></li>
	<li><%= @animal [2] %></li>
	<li><%= @animal [3] %></li>
	<li><%= @animal [4] %></li>
	<li><%= @animal [5] %></li>
</ul>
<hr>
<ul>
	<% @animal.each do |x| %>
	<li>
		<%= x %>
	</li>
	<% end %>
</ul>
<ol>
	<li>Toothpaste</li>
	<li>Toilet paper</li>
	<li>Cat food</li>
</ol>
<table class="table table-hover">
	<tr>
		<th>Name</th>
		<th>DOB</th>
		<th>email</th>
	</tr>
	<tr>
		<td>Robert Nixon</td>
		<td>10/10/1970</td>
		<td>robert.nixon@mac.com</td>
	</tr>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">&nbsp;RND&nbsp;</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/profiles">Profiles</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/profiles">Profiles</a></li>
            <li><a href="/status_updates">Status Updates</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <% if current_user.profile %>
             <li><a href="<% profile_path(current_user.profile) %>">My Profile</a></li>
            <% end %>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
        </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firstapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
<%= yield %>
<div>

</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :hobbies %>
    <%= f.input :dob %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hobbies</th>
      <th>Dob</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.hobbies %></td>
        <td><%= profile.dob %></td>
        <td><%= profile.user.email %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-default">
  <%= link_to 'New Profile', new_profile_path %>
</button>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-8">
	<%= render 'status_updates/form' %>
	<hr>
	<% @status_updates.each do |update| %>
		<div class="panel panel-warning">
			<div class="panel-heading">
				<p class="panel-title"><strong><%= update.title %></strong><br>
					<span class="pull right">
					Posted by: <%= update.user.profile.name %> 
					at <%= update.created_at.strftime('%H:%M') %>
					</span>
				</p>
			</div>
		</div>
	<% end %>
</div>

<div class="col-md-4">

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @profile.hobbies %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @profile.dob %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

</div>

app/views/status_updates/_form.html.erb
<%= simple_form_for(@status_update) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <!-- <%= f.association :user %> -->
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing status_update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<h1>Listing status updates</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.user %></td>
        <td><%= status_update.title %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New status_update</h1>

<%= render 'form' %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @status_update.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @status_update.title %>
</p>

<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>